export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_ITEMS = 'GET_ITEMS'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'

export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS'

export const GET_PERSONAL_DATA = 'GET_PERSONAL_DATA'

export const GET_CATEGORIES = 'GET_CATEGORIES'